sudo: required

language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - yes | pecl install imagick
  - sudo sed -i -e 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
  - sudo apt-get install -y ghostscript
  - travis_retry composer update --prefer-source $COMPOSER_FLAGS
  - travis_retry composer require league/flysystem-aws-s3-v3

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
